### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by liuyang12** [ThomasLee969/net.tsinghua#17]
I am wondering why is not there any Android version for net.tsinghua. If so, I will prefer AtTsinghua app to manager my online accounts.

**Comment by ClumsyLee** [comment]
Because net.tsinghua is based on [Electron](http://electron.atom.io), whose goal is to "Build cross platform desktop apps with web technologies".

Apart from that, [TUNet](http://tunet.lab.mu) developed by lab µ is really pretty enough. Forget about AtTsinghua and try it!
