### ISSUE TITLE
windows10上线失败

### ISSUE THREAD

**Issue by chongluyao** [ThomasLee969/net.tsinghua#22]
系统：windows10专业版
问题：
- 填写账号信息登陆后，不能显示在线设备。
- 点击下线可以下线成功，之后再点击上线按钮后无法上线。

**Comment by ClumsyLee** [comment]
怀疑是账号正确密码错误，然后是本机本身就已经在线了？这种情况下会显示在线，当前流量和下线操作不受影响，但是无法显示在线设备，无法上线。

**Comment by b-z** [comment]
但是她可以正常显示账户信息，包括余额等等
_(:з」∠)_

**Comment by ClumsyLee** [comment]
对的，因为这些信息不需要密码，是通过直接访问 https://net.tsinghua.edu.cn/rad_user_info.php 得到的~
密码错误的话目前不会有提示，之后的版本中应该会改进QAQ

**Comment by ClumsyLee** [comment]
请问解决了嘛QAQ

**Comment by chongluyao** [comment]
啊啊是的已经解决啦，确实是密码错误，不好意思><

**Comment by ClumsyLee** [comment]
嗯嗯那就好QAQ
