### ISSUE TITLE
Mac版求签名

### ISSUE THREAD

**Issue by liboyue** [ThomasLee969/net.tsinghua#29]
要不然还得按着ctrl才能打开。。。

**Comment by ClumsyLee** [comment]
Mac版签名需要 Apple Developer ID，每年要交保护费，目前看来有点亏QAQ

现在是有自签名的，不过没有什么卵用orz

我了解的是要右键>打开，原来 ctrl 也可以是吗，学习了orz

**Comment by liboyue** [comment]
还有个问题，retina屏图标糊。。。

**Comment by ClumsyLee** [comment]
是菜单栏上面的图标吗？app的图标是包括了 retina屏的2x分辨率版本的QAQ

**Comment by liboyue** [comment]
然而是糊的。。。 - -
貌似OS X的不要钱？（表示并不清楚。。。）

**Comment by liboyue** [comment]
原来是要钱的 ￥688 一年。。。跪了- -

**Comment by ClumsyLee** [comment]
![screen shot 2015-10-26 at 5 15 37 pm](https://cloud.githubusercontent.com/assets/7030671/10725200/326f4902-7c05-11e5-86fa-805cf2deac6e.png)
你说的是这个图标糊了嘛，菜单栏的呢，是两个都是糊的嘛orz

我是 MBA，木有 Retina 屏测试orz

**Comment by ClumsyLee** [comment]
嗯嗯，Windows下面直接信任的证书也不便宜，大概也要 100刀/年，全签名就要一年上千RMB了，感觉有点没必要orz

**Comment by liboyue** [comment]
别处的都是正常的，就是顶上的菜单栏 - - 懒得贴图了。。。

**Comment by ClumsyLee** [comment]
嗯对对，那个现在只有一个 16x16 的，没有匹配 Retina，我新开一个 issue #30 吧
