### ISSUE TITLE
谁想要一个死的 app？

### ISSUE THREAD

**Issue by ladyrick** [ThomasLee969/net.tsinghua#37]
# 永远崭新
谁想要一个死的 app？
任何更新都会被自动安装，而这一切完全是后台进行的。
安心吧，版本控们 —— 我们是一家人。

**Comment by ClumsyLee** [comment]
实在抱歉，最近在实习，实在是没有时间。
有了 CampNet 之后一直想重写 net.tsinghua，但那边也准备更新，这边的优先级应该会稍微低一些。
理想情况是，最后两边共享配置文件，之后就只需要更新配置文件了。
